### PR TITLE
port to meson

### PR DESCRIPTION
**Pull request by bil-elmoussaoui**
The work is still in progress. @JasonLG1979 Can you test it and see if anything doesn't work? there's still some missing stuff

### CODE REVIEW

**Comment by JasonLG1979** [comment]
Awesome man!!! will do!!!

**Comment by JasonLG1979** [comment]
It builds but I can't install it. It could just be me. I'm not a build guy. The only real thing I know about Meson is that it's much simpler than make and apparently it's still smarter than me,lol!!!

**Comment by bil-elmoussaoui** [comment]
as i've said it's still not ready yet :P The js, css files must be installed on /home/username/.local/share/gnome-shell/extensions
But where the gschema & locale files should be installed in order to work correctly with the extension?

**Comment by JasonLG1979** [comment]
Everything goes in /home/username/.local/share/gnome-shell/extensions/

**Comment by JasonLG1979** [comment]
If you download and extract one of my releases you'll see the file structure.

**Comment by JasonLG1979** [comment]
For it to be drop in replacement you'll need 2 install options(local and system wide) and an option to build a zip file.

**Comment by bil-elmoussaoui** [comment]
Few issues were fixed in my latest commit. Now the gschema is installed in the correct directory and compiled. The only remained issue is that we can't set a different location to install the locale files using meson.build files. You will need to run `meson builddir --prefix=/home/username/.local --localedir=/home/username/.local/share/gnome-shell/extensions/extname/locale`

This should be reported upstream to meson as with the current status, you can't use ninja without a root permission as the locale files will be installed by default in /usr/local

**Comment by JasonLG1979** [comment]
that's pretty cumbersome

**Comment by bil-elmoussaoui** [comment]
I will see if i can get any answer from meson guys at #freenode. Otherwise this PR should be kept open unless a fix lands upstream

**Comment by JasonLG1979** [comment]
It'll be open until it's ready. This is something I want done. Thanks.

**Comment by bil-elmoussaoui** [comment]
The build now works.
You can use  to install it locally
```bash
meson builddir --prefix=$HOME/.local
ninja -C builddir install
```
or 
```bash
meson builddir --prefix=/usr
sudo ninja -C builddir install
```
to install it globally.

**Comment by bil-elmoussaoui** [comment]
For building a zip file, this can be done pretty easily using a bash script. You can just build your extension in a tmp directory and zip that directory after that. 
One last question,
 in metadata.json, if the extension was built locally, where the locale path should point to ? it should include the home path too?

**Comment by JasonLG1979** [comment]
> For building a zip file, this can be done pretty easily using a bash script.

Then we'll need that script then too for it to be a drop in replacement.

> in metadata.json, if the extension was built locally, where the locale path should point to ? it should include the home path too?

The extension should be able to tell where to grab it's own locale.

https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/src/lib.js#L45-L56

**Comment by JasonLG1979** [comment]
In my mind to make it as easy as possible you could wrap it all in bash script. So you could do something like:

```./build --install-local```
To build and install locally and get any error and what not.

```./build --install-system-wide```
To build and install system wide and get any error and what not. and be prompted for a sudo password when needed.

 ```./build --zip-file```
To build and the zip file and get any error and what not.

**Comment by JasonLG1979** [comment]
I'll give it a test and merge it if all goes well. Thanks again!!!

**Comment by JasonLG1979** [comment]
I may need some help editing the wiki with new install instructions mostly with dependencies. The actual build instructions are stupid simple.

**Comment by JasonLG1979** [comment]
I hate to ask for more but what about uninstalling?

**Comment by bil-elmoussaoui** [comment]
The uninstalling can be done using Gnome Tweak Tool or the extensions.gnome.org. Is it really needed here?

**Comment by JasonLG1979** [comment]
You can't uninstall an extension installed system wide with tweak tool

**Comment by JasonLG1979** [comment]
So lets just ditch the system wide install option and change --install-local to just --install. In my mind extensions should be installed on a user by user basis anyway.

**Comment by JasonLG1979** [comment]
If a user wants to install the extension on multiple user accounts they can build the zip file or they can (cringe) install the distro packaged version of the extension. Really though the right way to install the extension is from the extensions site.

**Comment by JasonLG1979** [comment]
It builds and installs locally fine but your Yes/No loop never breaks out after that if I try to build the zip. What's the use of ever keeping the builddir around after it's build and installed? Can't we just delete it every time after we're done?

**Comment by bil-elmoussaoui** [comment]
It's being removed once the installation is done :+1:

**Comment by JasonLG1979** [comment]
Or even better.
```bash
#!/usr/bin/sh

# Possible arguments
#./build --install
#To build and install locally.

#./build --zip-file
#To build and the zip file.

BUILD_DIR="builddir"
LOCAL_PREFIX="$HOME/.local"
UUID="mediaplayer@patapon.info"
TMP_DIR="/tmp/share/gnome-shell/extensions/$UUID"

build_type=$1
if [ -z $build_type ]; then
  build_type="--install"
fi

case $build_type in
  "--install"*)
      meson $BUILD_DIR --prefix=$LOCAL_PREFIX
      ninja -C $BUILD_DIR install
      rm -rf "./$BUILD_DIR"
  ;;
  "--zip-file"*)
      meson $BUILD_DIR --prefix=/tmp
      ninja -C $BUILD_DIR install
      dest=$PWD
      cd $TMP_DIR
      zip -rq $dest/$UUID.zip .
      rm -rf $TMP_DIR
  ;;
esac
echo "Done"
```

**Comment by JasonLG1979** [comment]
Works like a charm. Now squash all that down to 1 commit and I'll merge it.

**Comment by JasonLG1979** [comment]
Never mind I can squash it.

**Comment by bil-elmoussaoui** [comment]
Is everything else works as expected?

**Comment by JasonLG1979** [comment]
There all done. We'll fix anything weird we find. In the mean time I need to fix the dependencies on the wiki.

**Comment by bil-elmoussaoui** [comment]
If you have any question/issue, just ping me here or on Twitter :) Thanks for the great extension! Keep up the great work

**Comment by JasonLG1979** [comment]
Thank You!!! Build stuff is not my area of interest or expertise.

**Pull request merged**
